import type { College } from "./types"

export const collegesData: College[] = [
  {
    id: "1",
    name: "IIT Madras",
    location: {
      city: "Chennai",
      state: "Tamil Nadu",
    },
    type: "Government",
    rating: 4.8,
    reviews: 9,
    fees: {
      min: 5000,
      max: 231000,
    },
    ranking: {
      nirf: 1,
      category: "Engineering",
    },
    image: "/iit-madras-campus-aerial-view.jpg",
    description:
      "IIT Chennai also known as IIT Madras is the top-ranked engineering college in India as per NIRF ranking, and the institute also holds a good rank in world university rankings. IIT Chennai is popular for its engineering programmes - B.Tech and M.Tech in various specialisations.",
    established: 1959,
    accreditation: ["AICTE", "UGC", "NBA"],
    streams: ["Engineering", "IT"],
    courses: [
      {
        id: "c1",
        name: "B.Tech Computer Science",
        duration: "4 years",
        fees: 200000,
        eligibility: "JEE Advanced",
        seats: 120,
      },
      {
        id: "c2",
        name: "M.Tech Data Science",
        duration: "2 years",
        fees: 150000,
        eligibility: "GATE",
        seats: 60,
      },
    ],
    facilities: ["Library", "Sports Complex", "Wi-Fi", "Medical", "Transportation", "Cafeteria", "Labs", "Auditorium"],
    hostel: {
      boys: true,
      girls: true,
    },
    studyMode: ["Full-time"],
    admissionProcess: {
      exams: ["JEE Advanced", "GATE"],
      criteria: "Merit-based selection through JEE Advanced for B.Tech and GATE for M.Tech programs",
    },
    placement: {
      averagePackage: 1800000,
      highestPackage: 10000000,
      placementRate: 95,
      topRecruiters: ["Google", "Microsoft", "Amazon", "Goldman Sachs", "McKinsey"],
    },
    campusLife: {
      studentStrength: 10000,
      facultyRatio: "1:8",
      clubs: ["Robotics Club", "Cultural Society", "Sports Club", "Literary Society"],
    },
    gallery: [
      "/iit-madras-main-building.jpg",
      "/iit-madras-library.jpg",
      "/iit-madras-hostel.jpg",
      "/iit-madras-sports-complex.jpg",
    ],
    reviews_data: [
      {
        id: "r1",
        studentName: "Rahul Kumar",
        rating: 5,
        comment: "Excellent faculty and infrastructure. Great placement opportunities.",
        course: "B.Tech CSE",
        year: 2023,
        date: "2024-01-15",
      },
    ],
  },
  {
    id: "2",
    name: "IIT Delhi",
    location: {
      city: "New Delhi",
      state: "Delhi",
    },
    type: "Government",
    rating: 4.7,
    reviews: 12,
    fees: {
      min: 8000,
      max: 250000,
    },
    ranking: {
      nirf: 2,
      category: "Engineering",
    },
    image: "/iit-delhi-campus-main-gate.jpg",
    description:
      "IIT Delhi is one of the premier engineering institutions in India, known for its cutting-edge research and excellent academic programs. The institute offers undergraduate, postgraduate, and doctoral programs in various engineering disciplines.",
    established: 1961,
    accreditation: ["AICTE", "UGC", "NBA"],
    streams: ["Engineering", "IT"],
    courses: [
      {
        id: "c3",
        name: "B.Tech Mechanical Engineering",
        duration: "4 years",
        fees: 220000,
        eligibility: "JEE Advanced",
        seats: 100,
      },
      {
        id: "c4",
        name: "MBA",
        duration: "2 years",
        fees: 400000,
        eligibility: "CAT",
        seats: 80,
      },
    ],
    facilities: ["Library", "Sports Complex", "Wi-Fi", "Medical", "Transportation", "Cafeteria", "Labs", "Auditorium"],
    hostel: {
      boys: true,
      girls: true,
    },
    studyMode: ["Full-time"],
    admissionProcess: {
      exams: ["JEE Advanced", "CAT", "GATE"],
      criteria: "Merit-based selection through respective entrance examinations",
    },
    placement: {
      averagePackage: 1700000,
      highestPackage: 12000000,
      placementRate: 93,
      topRecruiters: ["Microsoft", "Google", "Amazon", "Flipkart", "Uber"],
    },
    campusLife: {
      studentStrength: 8500,
      facultyRatio: "1:9",
      clubs: ["Photography Club", "Dance Society", "Debate Club", "Tech Club"],
    },
    gallery: [
      "/iit-delhi-academic-block.jpg",
      "/iit-delhi-student-center.jpg",
      "/iit-delhi-research-lab.jpg",
      "/iit-delhi-campus-green-area.jpg",
    ],
    reviews_data: [
      {
        id: "r2",
        studentName: "Priya Sharma",
        rating: 4,
        comment: "Great academic environment and research opportunities.",
        course: "M.Tech",
        year: 2023,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: "3",
    name: "BITS Pilani",
    location: {
      city: "Pilani",
      state: "Rajasthan",
    },
    type: "Private",
    rating: 4.6,
    reviews: 15,
    fees: {
      min: 350000,
      max: 450000,
    },
    ranking: {
      nirf: 25,
      category: "Engineering",
    },
    image: "/bits-pilani-campus-clocktower.jpg",
    description:
      "BITS Pilani is a premier private technological university known for its innovative curriculum and excellent industry connections. The institute offers integrated programs and has a strong alumni network in top companies worldwide.",
    established: 1964,
    accreditation: ["AICTE", "UGC"],
    streams: ["Engineering", "IT"],
    courses: [
      {
        id: "c5",
        name: "B.E. Computer Science",
        duration: "4 years",
        fees: 400000,
        eligibility: "BITSAT",
        seats: 150,
      },
      {
        id: "c6",
        name: "M.Sc. Mathematics",
        duration: "2 years",
        fees: 300000,
        eligibility: "BITSAT",
        seats: 40,
      },
    ],
    facilities: ["Library", "Sports Complex", "Wi-Fi", "Medical", "Transportation", "Cafeteria", "Labs"],
    hostel: {
      boys: true,
      girls: true,
    },
    studyMode: ["Full-time"],
    admissionProcess: {
      exams: ["BITSAT"],
      criteria: "Merit-based selection through BITSAT examination",
    },
    placement: {
      averagePackage: 1500000,
      highestPackage: 8000000,
      placementRate: 90,
      topRecruiters: ["Amazon", "Microsoft", "Goldman Sachs", "Adobe", "Cisco"],
    },
    campusLife: {
      studentStrength: 4000,
      facultyRatio: "1:12",
      clubs: ["Music Club", "Drama Club", "Entrepreneurship Cell", "Coding Club"],
    },
    gallery: [
      "/bits-pilani-library-interior.jpg",
      "/bits-pilani-hostel-rooms.jpg",
      "/bits-pilani-auditorium.jpg",
      "/bits-pilani-campus-festival.jpg",
    ],
    reviews_data: [
      {
        id: "r3",
        studentName: "Arjun Patel",
        rating: 5,
        comment: "Amazing campus culture and excellent placement support.",
        course: "B.E. CSE",
        year: 2022,
        date: "2024-01-20",
      },
    ],
  },
  {
    id: "4",
    name: "IIM Ahmedabad",
    location: {
      city: "Ahmedabad",
      state: "Gujarat",
    },
    type: "Government",
    rating: 4.9,
    reviews: 8,
    fees: {
      min: 2300000,
      max: 2500000,
    },
    ranking: {
      nirf: 1,
      category: "Management",
    },
    image: "/placeholder.svg?height=200&width=300",
    description:
      "IIM Ahmedabad is the premier management institute in India, known for its rigorous academic programs and exceptional placement records. The institute has produced numerous business leaders and entrepreneurs.",
    established: 1961,
    accreditation: ["AICTE", "AACSB"],
    streams: ["Management"],
    courses: [
      {
        id: "c7",
        name: "Post Graduate Programme in Management (PGP)",
        duration: "2 years",
        fees: 2500000,
        eligibility: "CAT",
        seats: 395,
      },
      {
        id: "c8",
        name: "Fellow Programme in Management (FPM)",
        duration: "4-5 years",
        fees: 100000,
        eligibility: "CAT/GMAT",
        seats: 30,
      },
    ],
    facilities: ["Library", "Sports Complex", "Wi-Fi", "Medical", "Cafeteria", "Auditorium"],
    hostel: {
      boys: true,
      girls: true,
    },
    studyMode: ["Full-time"],
    admissionProcess: {
      exams: ["CAT"],
      criteria: "CAT score, Academic Performance, Work Experience, and Personal Interview",
    },
    placement: {
      averagePackage: 3400000,
      highestPackage: 7000000,
      placementRate: 100,
      topRecruiters: ["McKinsey & Company", "Boston Consulting Group", "Bain & Company", "Goldman Sachs", "JP Morgan"],
    },
    campusLife: {
      studentStrength: 850,
      facultyRatio: "1:6",
      clubs: ["Consulting Club", "Finance Club", "Marketing Club", "Operations Club"],
    },
    gallery: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    reviews_data: [
      {
        id: "r4",
        studentName: "Sneha Gupta",
        rating: 5,
        comment: "World-class faculty and unparalleled learning experience.",
        course: "PGP",
        year: 2023,
        date: "2024-03-05",
      },
    ],
  },
  {
    id: "5",
    name: "Punjab Agricultural University",
    location: {
      city: "Ludhiana",
      state: "Punjab",
    },
    type: "Government",
    rating: 4.3,
    reviews: 6,
    fees: {
      min: 25000,
      max: 80000,
    },
    ranking: {
      nirf: 3,
      category: "Agriculture",
    },
    image: "/placeholder.svg?height=200&width=300",
    description:
      "Punjab Agricultural University is a leading agricultural university in India, known for its contributions to the Green Revolution. The university offers comprehensive programs in agriculture, veterinary sciences, and allied fields.",
    established: 1962,
    accreditation: ["ICAR", "UGC"],
    streams: ["Agriculture"],
    courses: [
      {
        id: "c9",
        name: "B.Sc. Agriculture",
        duration: "4 years",
        fees: 60000,
        eligibility: "Class 12 with PCM/PCB",
        seats: 200,
      },
      {
        id: "c10",
        name: "M.Sc. Agronomy",
        duration: "2 years",
        fees: 40000,
        eligibility: "B.Sc. Agriculture",
        seats: 50,
      },
    ],
    facilities: ["Library", "Research Farms", "Wi-Fi", "Medical", "Transportation", "Cafeteria", "Labs"],
    hostel: {
      boys: true,
      girls: true,
    },
    studyMode: ["Full-time"],
    admissionProcess: {
      exams: ["PAU CET"],
      criteria: "Merit-based selection through entrance examination and academic performance",
    },
    placement: {
      averagePackage: 400000,
      highestPackage: 1200000,
      placementRate: 75,
      topRecruiters: ["IFFCO", "Mahindra Agri", "Bayer CropScience", "Syngenta", "UPL"],
    },
    campusLife: {
      studentStrength: 3500,
      facultyRatio: "1:15",
      clubs: ["Agriculture Club", "Environmental Club", "Rural Development Society", "Farmers Club"],
    },
    gallery: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    reviews_data: [
      {
        id: "r5",
        studentName: "Harpreet Singh",
        rating: 4,
        comment: "Great practical exposure and research opportunities in agriculture.",
        course: "B.Sc. Agriculture",
        year: 2022,
        date: "2024-02-28",
      },
    ],
  },
  {
    id: "6",
    name: "IIIT Hyderabad",
    location: {
      city: "Hyderabad",
      state: "Telangana",
    },
    type: "Public",
    rating: 4.5,
    reviews: 11,
    fees: {
      min: 200000,
      max: 300000,
    },
    ranking: {
      nirf: 15,
      category: "Engineering",
    },
    image: "/placeholder.svg?height=200&width=300",
    description:
      "IIIT Hyderabad is a premier institute focused on information technology and computer science education. Known for its research-oriented approach and strong industry partnerships, it produces highly skilled IT professionals.",
    established: 1998,
    accreditation: ["AICTE", "UGC"],
    streams: ["IT", "Engineering"],
    courses: [
      {
        id: "c11",
        name: "B.Tech Computer Science",
        duration: "4 years",
        fees: 280000,
        eligibility: "JEE Main",
        seats: 120,
      },
      {
        id: "c12",
        name: "M.Tech Artificial Intelligence",
        duration: "2 years",
        fees: 200000,
        eligibility: "GATE",
        seats: 40,
      },
    ],
    facilities: ["Library", "Sports Complex", "Wi-Fi", "Medical", "Cafeteria", "Labs", "Auditorium"],
    hostel: {
      boys: true,
      girls: true,
    },
    studyMode: ["Full-time"],
    admissionProcess: {
      exams: ["JEE Main", "GATE"],
      criteria: "Merit-based selection through JEE Main for B.Tech and GATE for M.Tech",
    },
    placement: {
      averagePackage: 1600000,
      highestPackage: 9000000,
      placementRate: 95,
      topRecruiters: ["Google", "Microsoft", "Amazon", "Facebook", "Adobe"],
    },
    campusLife: {
      studentStrength: 2000,
      facultyRatio: "1:10",
      clubs: ["Coding Club", "AI/ML Club", "Robotics Club", "Gaming Club"],
    },
    gallery: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    reviews_data: [
      {
        id: "r6",
        studentName: "Ananya Reddy",
        rating: 5,
        comment: "Excellent research opportunities and industry exposure.",
        course: "B.Tech CSE",
        year: 2023,
        date: "2024-01-12",
      },
    ],
  },
]

export const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
]

export const streams = ["Engineering", "Management", "Agriculture", "IT"]

export const exams = [
  "JEE Main",
  "JEE Advanced",
  "GATE",
  "CAT",
  "BITSAT",
  "VITEEE",
  "SRMJEEE",
  "COMEDK",
  "MHT CET",
  "KCET",
  "EAMCET",
  "WBJEE",
  "OJEE",
  "GUJCET",
  "UPSEE",
]

export const facilities = [
  "Library",
  "Sports Complex",
  "Wi-Fi",
  "Medical",
  "Transportation",
  "Cafeteria",
  "Labs",
  "Auditorium",
]
